# Generated by Django 5.2.4 on 2025-09-26 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateField(default=django.utils.timezone.now)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='partidas.historicopartida')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='audios/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='midia.definicao')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='imagens/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='midia.definicao')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='videos/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='midia.definicao')),
            ],
        ),
    ]
