# Generated by Django 5.2.6 on 2025-09-24 01:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True)),
                ('criado_em', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='audios/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='midia.definicao')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='Imagens/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagens', to='midia.definicao')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='videos/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='midia.definicao')),
            ],
        ),
    ]
