# Generated by Django 5.2.6 on 2025-09-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('midia', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='partidas.historicopartida'),
        ),
        migrations.AddField(
            model_name='audio',
            name='definicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='midia.definicao'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='definicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='midia.definicao'),
        ),
        migrations.AddField(
            model_name='video',
            name='definicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='midia.definicao'),
        ),
    ]
