# Generated by Django 5.2.6 on 2025-10-12 21:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
        ('partidas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.URLField(max_length=300, verbose_name='Link do Jogo')),
                ('usuario', models.CharField(default='Anônimo', max_length=200)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_assistir', to='partidas.partida', verbose_name='Partida Associada')),
            ],
        ),
    ]
