# Generated by Django 5.2.4 on 2025-09-17 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEstadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(max_length=100)),
                ('tipo_emocao', models.CharField(choices=[('alegria', 'Alegria'), ('raiva', 'Raiva'), ('tensao', 'Tensão'), ('euforia', 'Euforia'), ('tristeza', 'Tristeza'), ('surpresa', 'Surpresa')], max_length=20)),
                ('intensidade', models.IntegerField()),
                ('comentario', models.TextField(null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
