# Generated by Django 5.2.6 on 2025-09-24 01:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoEstadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(max_length=100)),
                ('tipo_emocao', models.CharField(choices=[('alegria', 'Alegria'), ('raiva', 'Raiva'), ('tensao', 'Tensão'), ('euforia', 'Euforia'), ('tristeza', 'Tristeza'), ('surpresa', 'Surpresa')], max_length=20)),
                ('intensidade', models.IntegerField()),
                ('comentario', models.TextField(null=True)),
                ('avaliacao_experiencia', models.IntegerField(choices=[(1, '★☆☆☆☆ - Ruim'), (2, '★★☆☆☆ - Fraca'), (3, '★★★☆☆ - Média'), (4, '★★★★☆ - Boa'), (5, '★★★★★ - Incrível')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoTorcida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_torcida', models.TextField(blank=True, null=True)),
                ('emocao', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('presenca', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='emocao.time')),
            ],
        ),
    ]
