# Generated by Django 5.2.6 on 2025-09-27 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('time_id', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Definicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateField(default=django.utils.timezone.now)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.historicopartida')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='imagens/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.definicao')),
            ],
        ),
    ]
