# Generated by Django 5.2.6 on 2025-09-27 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='audios/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.definicao')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='videos/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.definicao')),
            ],
        ),
    ]
