# Generated by Django 5.2.6 on 2025-10-15 01:09

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/thumbnails/'),
        ),
        migrations.AddField(
            model_name='partida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.ImageField(upload_to='imagens/', validators=[core.models.validar_tamanho_arquivo]),
        ),
        migrations.AlterField(
            model_name='video',
            name='arquivo',
            field=models.FileField(upload_to='videos/', validators=[core.models.validar_tamanho_arquivo]),
        ),
    ]
