# Generated by Django 5.2.6 on 2025-10-16 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagem_thumbnail_partida_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='definicoes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
