# Generated by Django 5.2.6 on 2025-10-27 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaotorcida',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_torcida', to='core.partida'),
        ),
        migrations.AddField(
            model_name='avaliacaotorcida',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_torcida', to=settings.AUTH_USER_MODEL),
        ),
    ]
