# Generated by Django 5.2.4 on 2025-10-17 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_definicao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Link')),
                ('url', models.URLField(max_length=2000, verbose_name='URL do Link (Ex: YouTube)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('definicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.definicao')),
            ],
        ),
    ]
