# Generated by Django 5.2.7 on 2025-11-05 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacaotorcida_partida_avaliacaotorcida_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='definicao',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definicoes', to='core.partida'),
        ),
        migrations.AlterField(
            model_name='definicao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definicoes_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
