# Generated by Django 5.2.4 on 2025-10-17 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='nome_do_jogo',
            field=models.CharField(default='Jogo Desconhecido', max_length=200, verbose_name='Nome do Jogo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='definicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='core.definicao'),
        ),
        migrations.AlterField(
            model_name='link',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Link'),
        ),
    ]
