# Generated by Django 5.2.6 on 2025-09-26 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaopartida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gol',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partidas.jogador'),
        ),
        migrations.AddField(
            model_name='avaliacaopartida',
            name='melhor_jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melhor_em_avaliacoes', to='partidas.jogador'),
        ),
        migrations.AddField(
            model_name='avaliacaopartida',
            name='pior_jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pior_em_avaliacoes', to='partidas.jogador'),
        ),
        migrations.AddField(
            model_name='gol',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='partidas.partida'),
        ),
        migrations.AddField(
            model_name='avaliacaopartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='partidas.partida'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_casa', to='partidas.time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_visitante', to='partidas.time'),
        ),
    ]
